---
name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-MariaDb-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/MariaDb/'
  tf-checks-PostgreSQL:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/PostgreSQL/'
  tf-checks-complete-mssql-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/complete-mssql/'
  tf-checks-complete-mysql-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/complete-mysql/'
  tf-checks-oracle_db-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/oracle_db/'
  tf-checks-replica-mysql-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './examples/replica-mysql/'
...
